# Generated by Django 2.0.2 on 2018-04-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
